# Generated by Django 4.1.3 on 2022-11-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='activies.clients'),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='produits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='activies.produits'),
        ),
    ]
