# Generated by Django 4.1.3 on 2022-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0002_alter_sorties_clients_alter_sorties_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='tvaPourcentage',
            field=models.FloatField(default='0.0'),
        ),
    ]
