# Generated by Django 4.1.3 on 2022-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0003_alter_sorties_tvapourcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrees',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sorties',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
