# Generated by Django 4.1.3 on 2022-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0004_entrees_prix_total_sorties_prix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinering',
            name='quantite_entree',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
