# Generated by Django 4.1.3 on 2022-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0005_refinering_quantite_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinering',
            name='teneur_sortie',
            field=models.FloatField(null=True),
        ),
    ]
