# Generated by Django 4.1.3 on 2022-11-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0006_alter_refinering_teneur_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrees',
            name='tvaPourcentage',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
