# Generated by Django 4.1.3 on 2022-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0007_alter_entrees_tvapourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrees',
            name='teneur',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='refinering',
            name='teneur_sortie',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='smelting',
            name='teneur_entrer',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='teneur',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
