# Generated by Django 4.1.3 on 2022-11-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
