# Generated by Django 4.1.3 on 2022-12-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0011_alter_clients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorties',
            options={'ordering': ['date_sortie']},
        ),
    ]
