# Generated by Django 4.1.3 on 2022-12-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0012_alter_sorties_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorties',
            options={'ordering': ['-date_sortie']},
        ),
    ]
