# Generated by Django 4.1.3 on 2022-12-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0013_alter_sorties_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-created_at']},
        ),
    ]
