# Generated by Django 4.1.3 on 2022-12-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
