# Generated by Django 4.1.3 on 2022-12-19 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0016_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 47, 49, 364902)),
        ),
    ]
