# Generated by Django 4.1.3 on 2023-01-01 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0017_alter_sorties_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 15, 53, 4, 645775)),
        ),
    ]
