# Generated by Django 4.1.3 on 2022-12-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0018_alter_sorties_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default='2022-12-19 15:10:01.548971'),
        ),
    ]
