# Generated by Django 4.1.3 on 2022-12-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0021_alter_sorties_date_sortie_alter_users_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default='2022-12-19 20:47:17.365919'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 20, 47, 17, 370920)),
        ),
        migrations.AlterField(
            model_name='users',
            name='image_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
