# Generated by Django 4.1.3 on 2022-12-19 23:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activies', '0027_alter_sorties_date_sortie_alter_users_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorties',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default='2022-12-20 00:18:03.443931'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 18, 3, 443931)),
        ),
    ]
