# Generated by Django 4.1.3 on 2022-12-19 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0029_alter_sorties_date_sortie_alter_users_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 42, 13, 458920)),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activies.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 42, 13, 458920)),
        ),
    ]
