# Generated by Django 4.1.3 on 2022-12-19 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0030_alter_sorties_date_sortie_alter_sorties_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 42, 19, 540920)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 42, 19, 540920)),
        ),
    ]
