# Generated by Django 4.1.3 on 2022-12-19 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activies', '0033_alter_sorties_date_sortie_alter_users_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 51, 4, 71919)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 0, 51, 4, 71919)),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
