# Generated by Django 4.1.3 on 2023-11-27 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0035_alter_sorties_date_sortie_alter_sorties_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 22, 23, 36, 306811)),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 22, 23, 36, 306811)),
        ),
    ]
