# Generated by Django 4.1.3 on 2023-11-28 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0037_entrees_user_refinering_user_smelting_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrees',
            name='teneur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 28, 33, 305095)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 28, 33, 305095)),
        ),
    ]
