# Generated by Django 4.1.3 on 2023-11-28 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0039_remove_refinering_quantite_entree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='depanses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='transport', max_length=222, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrees',
            name='montant_depanses',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 18, 37, 913862)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 14, 18, 37, 913862)),
        ),
        migrations.AddField(
            model_name='entrees',
            name='depanses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activies.depanses'),
        ),
    ]
