# Generated by Django 4.1.3 on 2023-11-28 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0040_depanses_entrees_montant_depanses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrees',
            name='prix_total',
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 25, 4, 739986)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 25, 4, 739986)),
        ),
    ]
