# Generated by Django 4.1.3 on 2023-11-28 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0041_remove_entrees_prix_total_alter_sorties_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 27, 12, 751112)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 27, 12, 751112)),
        ),
    ]
