# Generated by Django 4.1.3 on 2023-11-28 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0042_alter_sorties_date_sortie_alter_users_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrees',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 32, 10, 103988)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 32, 10, 103988)),
        ),
    ]
