# Generated by Django 4.1.3 on 2023-11-28 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0043_entrees_prix_total_alter_sorties_date_sortie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrees',
            name='prix_total',
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 38, 8, 377736)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 38, 8, 377736)),
        ),
    ]
