# Generated by Django 4.1.3 on 2023-01-11 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0044_remove_entrees_prix_total_alter_sorties_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 2, 23, 266846)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 2, 23, 266846)),
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('livree', 'livree'), ('non_livree', 'non_livree')], max_length=20)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantite', models.FloatField()),
                ('teneur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tvaPourcentage', models.FloatField(default='0.0')),
                ('date_sortie', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 2, 23, 266846))),
                ('prix_total', models.FloatField(default=0.0)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='activies.clients')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activies.produits')),
            ],
        ),
    ]
