# Generated by Django 4.1.3 on 2023-01-12 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0047_alter_commande_date_sortie_alter_commande_prix_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrees',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 9, 27, 33, 840784)),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 9, 27, 33, 845783)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 9, 27, 33, 845783)),
        ),
    ]
