# Generated by Django 4.1.3 on 2023-01-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0049_alter_commande_date_sortie_alter_sorties_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 31, 197031)),
        ),
        migrations.AlterField(
            model_name='entrees',
            name='montant_depanses',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 31, 197031)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 31, 197031)),
        ),
    ]
