# Generated by Django 4.1.3 on 2023-01-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0050_alter_commande_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 36, 774658)),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 36, 774658)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 10, 2, 36, 774658)),
        ),
    ]
