# Generated by Django 4.1.3 on 2023-01-12 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0051_alter_commande_date_sortie_alter_sorties_date_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 11, 12, 4, 661102)),
        ),
        migrations.AlterField(
            model_name='sorties',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 11, 12, 4, 676728)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 11, 12, 4, 676728)),
        ),
    ]
