# Generated by Django 4.1.3 on 2023-01-19 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0053_transformations_remove_smelting_fourcasterie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 20, 57, 33, 506884)),
        ),
        migrations.AlterField(
            model_name='transformations',
            name='fourrafine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activies.fourrafine'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 20, 57, 33, 506884)),
        ),
    ]
