# Generated by Django 4.1.3 on 2023-01-19 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0054_alter_commande_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 0, 18, 619531)),
        ),
        migrations.AlterField(
            model_name='fourrafine',
            name='libelle',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 0, 18, 619531)),
        ),
    ]
