# Generated by Django 4.1.3 on 2023-01-19 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0055_alter_commande_date_sortie_alter_fourrafine_libelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrees',
            name='date_sortie',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 33, 57, 84636)),
        ),
        migrations.AlterField(
            model_name='fourrafine',
            name='libelle',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 33, 57, 100259)),
        ),
    ]
