# Generated by Django 4.1.3 on 2023-01-19 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0056_entrees_date_sortie_alter_commande_date_sortie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrees',
            old_name='date_sortie',
            new_name='date_entrer',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_sortie',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 35, 20, 638508)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 21, 35, 20, 654639)),
        ),
    ]
