# Generated by Django 4.1.3 on 2023-01-19 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0057_rename_date_sortie_entrees_date_entrer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='tvaPourcentage',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commander',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 10, 9, 255505)),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livrer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 10, 9, 255505)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 10, 9, 260509)),
        ),
    ]
