# Generated by Django 4.1.3 on 2023-01-19 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0058_remove_commande_date_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commander',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livrer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 14, 2, 860651)),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 14, 2, 866504)),
        ),
    ]
