# Generated by Django 4.1.3 on 2023-01-19 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0060_alter_commande_date_livrer_alter_users_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_livrer',
            new_name='date_modifier',
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 20, 27, 349506)),
        ),
    ]
