# Generated by Django 4.1.3 on 2023-01-19 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0063_transformations_entrant_casterie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 52, 9, 30584)),
        ),
    ]
