# Generated by Django 4.1.3 on 2023-01-19 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0064_alter_users_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorties',
            name='tvaPourcentage',
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 53, 39, 313506)),
        ),
    ]
