# Generated by Django 4.1.3 on 2023-01-20 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0065_remove_sorties_tvapourcentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrees',
            options={'ordering': ['-date_entrer']},
        ),
        migrations.RenameField(
            model_name='entrees',
            old_name='montant_depanses',
            new_name='montant_depanses_en_dollard',
        ),
        migrations.RenameField(
            model_name='entrees',
            old_name='prix_achat',
            new_name='prix_achat_en_dollard',
        ),
        migrations.RenameField(
            model_name='entrees',
            old_name='prix_total',
            new_name='prix_total_en_dollard',
        ),
        migrations.RenameField(
            model_name='entrees',
            old_name='quantite',
            new_name='quantite_en_kg',
        ),
        migrations.RenameField(
            model_name='entrees',
            old_name='teneur',
            new_name='teneur_en_pourcentage',
        ),
        migrations.RenameField(
            model_name='sorties',
            old_name='prix_total',
            new_name='prix_total_en_dollard',
        ),
        migrations.RenameField(
            model_name='sorties',
            old_name='prix_vente',
            new_name='prix_vente_en_dollard',
        ),
        migrations.RenameField(
            model_name='sorties',
            old_name='quantite',
            new_name='quantite_en_kg',
        ),
        migrations.RenameField(
            model_name='sorties',
            old_name='teneur',
            new_name='teneur_en_pourcentage',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='entrant_casterie',
            new_name='entrant_casterie_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='entrant_etain',
            new_name='entrant_etain_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='quantite_entrer_casterie',
            new_name='quantite_entrer_casterie_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='quantite_entrer_etain',
            new_name='quantite_entrer_etain_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='quantite_sortie_casterie',
            new_name='quantite_sortie_casterie_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='quantite_sortie_etain',
            new_name='quantite_sortie_etain_en_kg',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='teneur_casterie',
            new_name='teneur_casterie_en_pourcentage',
        ),
        migrations.RenameField(
            model_name='transformations',
            old_name='teneur_etain',
            new_name='teneur_etain_en_pourcentage',
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 10, 2, 29, 357320)),
        ),
    ]
