# Generated by Django 4.1.3 on 2023-01-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0066_alter_entrees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 10, 6, 28, 801193)),
        ),
    ]
