# Generated by Django 4.1.3 on 2023-01-20 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0072_alter_users_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_vente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='teneur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 16, 49, 50, 337934)),
        ),
    ]
