# Generated by Django 4.1.3 on 2023-01-20 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activies', '0073_alter_commande_prix_vente_alter_commande_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 16, 10, 49, 264614)),
        ),
    ]
